import fs from 'node:fs/promises'
await fs.mkdir('.qa-r02d2.local', { recursive: true })
export const delay = ms => new Promise(r => setTimeout(r,ms))
export async function connect() {
 const debugOrigin = 'http://127.0.0.1:'+(process.env.BROWSER_DEBUG_PORT ?? '9246')
 const targets = await (await fetch(`${debugOrigin}/json`)).json()
 const socket = new WebSocket(targets.find(t=>t.type==='page').webSocketDebuggerUrl)
 await new Promise(r=>socket.addEventListener('open',r,{once:true}))
 let id=0; const callbacks=new Map()
 socket.addEventListener('message',e=>{ const m=JSON.parse(e.data); if(callbacks.has(m.id)){ callbacks.get(m.id)(m); callbacks.delete(m.id) } })
 const call=(method,params={})=>new Promise((resolve,reject)=>{callbacks.set(++id,m=>m.error?reject(Error(m.error.message)):resolve(m.result));socket.send(JSON.stringify({id,method,params}))})
 const evaluate=async expression=>{const r=await call('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value}
 const wait=async expression=>{for(let i=0;i<100;i++){if(await evaluate(expression))return;await delay(100)}throw Error('Timeout: '+expression+' '+await evaluate('document.body.innerText'))}
 const go=async query=>{await call('Page.navigate',{url:(process.env.APP_ORIGIN ?? 'http://127.0.0.1:5186')+'/tests/explore.fixture.html'+query});await wait('!!document.querySelector(".results-count")')}
 const shot=async name=>{const r=await call('Page.captureScreenshot',{format:'png'});await fs.writeFile('.qa-r02d2.local/'+name+'.png',Buffer.from(r.data,'base64'))}
 const size=async width=>call('Emulation.setDeviceMetricsOverride',{width,height:900,deviceScaleFactor:1,mobile:false})
 const fill=async value=>evaluate('(()=>{const e=document.querySelector("#game-filter");e.focus();Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,"value").set.call(e,'+JSON.stringify(value)+');e.dispatchEvent(new Event("input",{bubbles:true}))})()')
 return {call,evaluate,wait,go,shot,size,fill,close:()=>socket.close()}
}

const {default:assert} = await import('node:assert/strict')
const b=await connect()
const count=async n=>b.wait('document.querySelector(".results-count")?.textContent === '+JSON.stringify(n+' '+(n===1?'resultado':'resultados')))
const param=async name=>b.evaluate('new URLSearchParams(location.search).get('+JSON.stringify(name)+')')
const click=async selector=>b.evaluate('document.querySelector('+JSON.stringify(selector)+').click()')
const key=async(key,code=key)=>{await b.call('Input.dispatchKeyEvent',{type:'keyDown',key,code,windowsVirtualKeyCode:({Enter:13,Tab:9,ArrowDown:40,Escape:27})[key]});if(key==='Enter')await b.call('Input.dispatchKeyEvent',{type:'char',text:'\r',unmodifiedText:'\r',key,windowsVirtualKeyCode:13});await b.call('Input.dispatchKeyEvent',{type:'keyUp',key,code,windowsVirtualKeyCode:({Enter:13,Tab:9,ArrowDown:40,Escape:27})[key]})}
const choose=async query=>{await b.fill(query);await b.wait('!!document.querySelector("[role=option]")');await key('ArrowDown');await key('Enter')}
try {
 await b.size(1440)
 await b.go('?game=cat&zone=Centro&keep=1');await count(3)
 assert.equal(await param('gameId'),null)
 assert.equal(await b.evaluate('window.exploreFixture.reads()'),0)
 await b.go('?game=Catan&gameId=catan');await count(2)
 await b.wait('window.exploreFixture.reads() === 1')
 assert.deepEqual(await b.evaluate('[...document.querySelectorAll(".session-card__link")].map(e=>e.getAttribute("href").split("/").at(-1))'),['cataloged','historical'])
 await b.call('Page.reload');await count(2)
 await b.wait('document.querySelector("#game-filter").value === "Catan"')
 await b.evaluate('window.exploreFixture.emit([...window.exploreFixture.sessions,{...window.exploreFixture.sessions[0],id:"live"}])');await count(3)
 await b.evaluate('window.exploreFixture.emit(window.exploreFixture.sessions.filter(s=>s.id!=="cataloged"))');await count(1)
 assert.equal(await b.evaluate('window.exploreFixture.reads()'),1)
 await b.go('?game=Catan&gameId=catan&catalogError=1');await count(3)
 await b.fill('cat');await b.wait('!!document.querySelector(".game-combobox__retry")');await count(4);await b.shot('catalog-error')
 await b.evaluate('window.exploreFixture.setCatalogFailure(false)');await click('.game-combobox__retry')
 await b.wait('document.querySelector("[role=option]")?.textContent === "Catan"')
 await key('ArrowDown');await key('Enter');await count(2)
 await b.go('?game=Catan&gameId=missing');await count(3)
 assert.equal(await param('gameId'),'missing')
 await b.go('?game=Catan&gameId=catan&date=today&zone=Centro&keep=1');await count(0)
 await click('[aria-label="Limpiar juego"]')
 assert.equal(await param('game'),null);assert.equal(await param('gameId'),null)
 assert.equal(await param('date'),'today');assert.equal(await param('zone'),'Centro')
 await click('.filters__clear');await count(17)
 assert.equal(await b.evaluate('location.search'),'?keep=1')
 await b.fill('cat');await count(4);assert.equal(await param('gameId'),null)
 await click('#zone-filter');await b.evaluate('[...document.querySelectorAll("[role=option]")].find(e=>e.textContent.trim()==="Retiro").click()');await count(1)
 assert.equal(await param('game'),'cat');assert.equal(await param('zone'),'Retiro')
 await b.evaluate('[...document.querySelectorAll(".date-chip")].find(e=>e.textContent.trim()==="Hoy").click()');await count(0)
 assert.equal(await param('date'),'today');assert.equal(await param('zone'),'Retiro')
 await click('.filters__clear');await count(17)
 await choose('Aventureros');await count(1)
 await b.wait('document.querySelector("#game-filter").value === "Ticket to Ride"')
 assert.equal(await param('game'),'Ticket to Ride');assert.equal(await param('gameId'),'ticket-to-ride')
 await b.fill('Inventado');await count(0);await b.wait('!!document.querySelector("[role=option]")')
 await key('Escape');assert.equal(await b.evaluate('document.querySelector("#game-filter").getAttribute("aria-expanded")'),'false')
 await key('ArrowDown');await b.wait('document.querySelector("#game-filter").getAttribute("aria-expanded") === "true"');await key('Enter')
 assert.equal(await param('game'),'Inventado');assert.equal(await param('gameId'),null)
 await click('.filters__clear');await count(17)
 assert.equal(await b.evaluate('document.querySelector("#game-filter").value'),'')
 // Real page, card origin, detail and browser back; fixture adapters only.
 await b.go('?game=Azul&gameId=azul&zone=Centro');await count(12)
 await b.evaluate('window.scrollTo(0,650)');await delay(150)
 const before=await b.evaluate('scrollY')
 await click('.session-card__link');await b.wait('!!document.querySelector(".session-detail") || !!document.querySelector(".detail-layout") || location.pathname.includes("/sessions/")');await delay(200)
 assert.equal(await b.evaluate('history.state.usr.from'), '/?game=Azul&gameId=azul&zone=Centro')
 await b.evaluate('history.back()');await count(12);await delay(300)
 assert.equal(await param('gameId'),'azul')
 assert.ok(Math.abs(await b.evaluate('scrollY')-before)<5,'Browser back must preserve scroll')
 await click('.session-card__link');await b.wait('!!document.querySelector(".breadcrumb") || !!document.querySelector(".breadcrumbs") || document.body.innerText.includes("Solicitar plaza")')
 const returnSelector = await b.evaluate('JSON.stringify([...document.querySelectorAll("a")].filter(e=>e.textContent.trim()==="Explorar").map(e=>e.getAttribute("href")))')
 console.log('Detail return candidates',returnSelector)
 await b.evaluate('[...document.querySelectorAll("a")].find(e=>e.textContent.trim()==="Explorar" && e.getAttribute("href").includes("gameId")).click()')
 await count(12);await delay(300)
 assert.equal(await param('gameId'),'azul')
 assert.ok(Math.abs(await b.evaluate('scrollY')-before)<5,'Visible return must preserve scroll')
 console.log('PASS URL, reload, catalog/historical/exclusion, alias keyboard, text/fallback, clearing, realtime and back/scroll')
 for(const width of [1440,375,400,320]) {
  await b.size(width);await b.go('?game=Catan');await count(3)
  await b.shot('after-'+width)
  if(width >= 375) assert.equal(await b.evaluate('document.documentElement.scrollWidth > document.documentElement.clientWidth'),false)
  await b.fill('X'.repeat(120));await b.wait('!!document.querySelector("[role=option]")')
  if(width >= 375) assert.equal(await b.evaluate('document.documentElement.scrollWidth > document.documentElement.clientWidth'),false)
  await b.shot('long-'+width)
  await b.fill('Aventureros');await b.wait('document.querySelector("[role=option]")?.textContent === "Ticket to Ride"')
  await b.shot('alias-'+width)
  await key('ArrowDown');await key('Enter');await count(1)
  await b.wait('document.querySelector("#game-filter").value === "Ticket to Ride"')
  await key('Tab');assert.equal(await b.evaluate('document.activeElement.getAttribute("aria-label")'),'Limpiar juego')
  await key('Enter');await count(17)
  assert.equal(await b.evaluate('document.activeElement.id'),'game-filter')
  console.log('PASS viewport '+width+' long fallback, alias and focus; geometry', await b.evaluate('({scroll:document.documentElement.scrollWidth,client:document.documentElement.clientWidth})'))
 }
 // Shared component retains default selection/required behavior used by Create/Edit.
 await b.call('Page.navigate',{url:(process.env.APP_ORIGIN ?? 'http://127.0.0.1:5186')+'/tests/game-combobox.fixture.html'})
 await b.wait('!!document.querySelector("#fixture-game")')
 await b.evaluate('(()=>{const e=document.querySelector("#fixture-game");e.focus();Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,"value").set.call(e,"Aventureros");e.dispatchEvent(new Event("input",{bubbles:true}))})()')
 await b.wait('document.querySelector("[role=option]")?.textContent === "Ticket to Ride"')
 await key('ArrowDown');await key('Enter')
 await b.wait('document.querySelector("#fixture-game").value === "Ticket to Ride"')
 assert.ok(await b.evaluate('document.querySelector("#fixture-selection").textContent.includes("ticket-to-ride")'))
 await click('[aria-label="Limpiar juego"]')
 await b.evaluate('[...document.querySelectorAll("label")].find(e=>e.textContent.includes("Selección obligatoria")).querySelector("input").click()')
 assert.equal(await b.evaluate('document.querySelector("form").checkValidity()'),false)
 console.log('PASS shared combobox default mode and required validation')
} finally {b.close()}
